# Generated by Django 5.0.7 on 2024-07-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='album_name',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
