# Generated by Django 5.0.7 on 2024-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_searchclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchclick',
            name='q',
            field=models.CharField(max_length=50),
        ),
    ]
