# Generated by Django 5.0.7 on 2024-07-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_searchclick_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
