# Generated by Django 5.0.7 on 2024-07-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_review_trackscore_review_unique_account_album_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Share',
            new_name='ShareClick',
        ),
    ]
