# Generated by Django 5.0.7 on 2024-07-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='best_new',
            field=models.BooleanField(default=False),
        ),
    ]
