# Generated by Django 5.0.7 on 2024-07-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_review_best_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='best_new',
            new_name='is_best_new',
        ),
    ]
