# Generated by Django 5.0.7 on 2024-07-30 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_best_new_review_is_best_new'),
        ('spotify', '0003_alter_search_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotify.album'),
        ),
    ]
