# Generated by Django 5.0.7 on 2024-07-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_review_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackscore',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_scores', to='api.review'),
        ),
    ]
