# Generated by Django 5.0.7 on 2024-07-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_trackscore_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchclick',
            name='q',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shareclick',
            name='album_name',
            field=models.CharField(default='Not specified', max_length=200),
        ),
    ]
