# Generated by Django 5.0.7 on 2024-07-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_searchclick_q_alter_shareclick_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumclick',
            name='album_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='searchclick',
            name='q',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shareclick',
            name='album_name',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
