# Generated by Django 5.0.7 on 2024-08-03 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_albumclick_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.account'),
        ),
    ]
