# Generated by Django 5.0.7 on 2025-09-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_account_user'),
        ('api', '0023_alter_review_text'),
    ]

    operations = [
    ]
