# Generated by Django 5.0.7 on 2024-11-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_review_account'),
        ('api', '0023_alter_account_user'),
        ('api', '0023_alter_review_text'),
    ]

    operations = [
    ]
